### ISSUE TITLE
Demo not working properly with wildfly 26.1.3

### ISSUE THREAD

**Issue by zedbeit** [wildfly-security-incubator/elytron-examples#165]
I tried to run the demo on Ubuntu 22.04 OS, but it wasn't working properly with wildfly 26.1.3, I keep getting a 404 error, but it worked when I Installed wildfly 27.0.1.

Here's a screenshot of the error
![wildflyerror](https://user-images.githubusercontent.com/57130151/219980503-767532aa-159d-4e11-840a-ea3bc9e195cc.png)

**Comment by fjuma** [comment]
@cam-rod Please a take a look whenever you get a chance, thanks!

**Comment by cam-rod** [comment]
Thanks for opening the issue. Like I mentioned [on Zulip](https://wildfly.zulipchat.com/#narrow/stream/173102-wildfly-elytron/topic/GSoC.202023.20Project.20Proposal/near/328323956), this is due to changes made for WildFly 27 and the migration to Jakarta EE 10. I don't see this particular issue being resolved as the main priority is supporting WildFly 27. I think what we can do is create a repo README instructing users to use the `1.x` branch for WildFly 26 and earlier, what do you think @fjuma?

Seperately, there seems to be an internal issue with this particular demo on 26.1.3. I feel that it may have worked on 26.1.2, but I didn't have a chance to test it. Attached the trace below:

```java
[INFO] --- exec-maven-plugin:3.0.0:exec (default-cli) @ ejb-http ---
Feb 21, 2023 12:40:32 PM org.wildfly.naming.client.Version <clinit>
INFO: WildFly Naming version 1.0.14.Final
Feb 21, 2023 12:40:32 PM org.wildfly.security.Version <clinit>
INFO: ELY00001: WildFly Elytron version 1.19.0.Final
Feb 21, 2023 12:40:32 PM org.xnio.Xnio <clinit>
INFO: XNIO version 3.8.4.Final
Feb 21, 2023 12:40:32 PM org.xnio.nio.NioXnio <clinit>
INFO: XNIO NIO Implementation Version 3.8.4.Final
Feb 21, 2023 12:40:32 PM org.jboss.threads.Version <clinit>
INFO: JBoss Threads version 2.4.0.Final
Feb 21, 2023 12:40:32 PM org.jboss.remoting3.EndpointImpl <clinit>
INFO: JBoss Remoting version 5.0.20.Final
Feb 21, 2023 12:40:32 PM org.jboss.ejb.client.EJBClient <clinit>
INFO: JBoss EJB Client version 4.0.39.Final
Exception in thread "main" java.lang.reflect.InaccessibleObjectException: Unable to make field private static final java.lang.reflect.Method jdk.proxy2.$Proxy2.m0 accessible: module jdk.proxy2 does not "opens jdk.proxy2" to unnamed module @7f0db310
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
	at org.jboss.ejb.client.EJBProxyInformation$1.doCompute(EJBProxyInformation.java:101)
	at org.jboss.ejb.client.EJBProxyInformation$1.computeValue(EJBProxyInformation.java:72)
	at org.jboss.ejb.client.EJBProxyInformation$1.computeValue(EJBProxyInformation.java:66)
	at java.base/java.lang.ClassValue.getFromHashMap(ClassValue.java:228)
	at java.base/java.lang.ClassValue.getFromBackup(ClassValue.java:210)
	at java.base/java.lang.ClassValue.get(ClassValue.java:116)
	at org.jboss.ejb.client.EJBProxyInformation.forViewType(EJBProxyInformation.java:242)
	at org.jboss.ejb.client.EJBLocator.getProxyInformation(EJBLocator.java:375)
	at org.jboss.ejb.client.EJBLocator.getProxyConstructor(EJBLocator.java:370)
	at org.jboss.ejb.client.EJBLocator.createProxyInstance(EJBLocator.java:387)
	at org.jboss.ejb.client.EJBClient.createProxy(EJBClient.java:161)
	at org.jboss.ejb.client.EJBRootContext.lookupNative(EJBRootContext.java:166)
	at org.wildfly.naming.client.AbstractContext.lookup(AbstractContext.java:84)
	at org.wildfly.naming.client.WildFlyRootContext.lookup(WildFlyRootContext.java:144)
	at java.naming/javax.naming.InitialContext.lookup(InitialContext.java:409)
	at org.wildfly.security.examples.RemoteClient.main(RemoteClient.java:49)
[ERROR] Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
    at org.apache.commons.exec.DefaultExecutor.executeInternal (DefaultExecutor.java:404)
    at org.apache.commons.exec.DefaultExecutor.execute (DefaultExecutor.java:166)
    at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:982)
    at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:929)
    at org.codehaus.mojo.exec.ExecMojo.execute (ExecMojo.java:457)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:301)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:211)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:165)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:157)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:121)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:127)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:294)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.503 s
[INFO] Finished at: 2023-02-21T12:40:32-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.0.0:exec (default-cli) on project ejb-http: Command execution failed.: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
```

**Comment by cam-rod** [comment]
Alright, I've opened #166 to track creating the README and other files (ex. license). 

Tested the build on 26.1.2.Final and it still failed, so it likely is some other issue.
